spring:
  application:
    name: teachmon-local
  config:
    import:
      - file:env/local.env[.properties]

  datasource:
    driver-class-name: ${MYSQL_DRIVER_NAME}
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            authorization-grant-type: ${GOOGLE_GRANT_TYPE}
            redirect-uri: ${GOOGLE_REDIRECT_URI}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

code:
  auth:
    expiration: ${CODE_EXPIRATION}

web:
  front-end-url: ${FRONTEND_URL}

google-spreadsheet:
  enabled: false
  credential-path: ${GOOGLE_SPREADSHEET_CREDENTIALS_PATH}
  application-name: ${GOOGLE_SPREADSHEET_APPLICATION_NAME}
  credentials-scope: ${GOOGLE_SPREADSHEET_CREDENTIALS_SCOPE}
  page: ${GOOGLE_SPREADSHEET_PAGE}

discord:
  webhook: ${DISCORD_WEBHOOK}